### ISSUE TITLE
Unsupported device on games

### ISSUE THREAD

**Issue by mahmutelmas06** [FreshROMs/fresh#26]
Your rom gives an error on some games that "The devices os or software is not compatible."

Device name or some other setting could be the issue for that.

**Comment by TenSeventy7** [comment]
Check if SafetyNet passes on your device as several apps now check if the device passes SafetyNet before being "compatible" on the Play Store. If it passes, clear Google Play Store data and wait for a few minutes and apps should now be compatible.

Otherwise, contact the app's developer as this is most likely an issue on their end.

**Comment by TenSeventy7** [comment]
Stale. Will close now.
